version: '3.8'
volumes:
  redis_data: {}
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
  dev-redis:
    image: redis:7-alpine
    container_name: projectsportfolio-dev-redis
    hostname: projectsportfolio-dev-redis
    environment:
      - REDIS_PASSWORD=password
    networks:
      - projectsportfolio
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  test-redis:
    image: redis:7-alpine
    container_name: projectsportfolio-test-redis
    hostname: projectsportfolio-test-redis
    environment:
      - REDIS_PASSWORD=password
    networks:
      - projectsportfolio
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6380:6379
networks:
      projectsportfolio: