version: "3.8"
services:
  dev-db:
    image: postgres:13
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    # env_file:
    #   - .env
    environment:
      DATABASE_URL: postgres://postgres:123@localhost:5432/projects-portfolio?schema=public
    volumes:
      - myapp:/usr/src/app
      - myapp:/usr/src/app/node_modules
    ports:
      - 3333:3333
    networks:
      - projectsportfolio
    # restart: on-failure
    links:
      - dev-db
    depends_on:
      - dev-db
  api-test:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env.test
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run test:e2e
    ports:
      - 3333:3333
    depends_on:
      - test-db
  test-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
networks:
      projectsportfolio:
        driver: bridge
volumes:
  myapp:
  docker-nest-postgres: